project title: Fieldwork Database Manager
database path: testDB.sqlite3

# you cannot include a field called id.  One will be made automatically for you
fields:
  name:
    datatype: text
    nullable: false
  date:
    datatype: datetime
    nullable: True
  count:
    datatype: integer
    nullable: True
  lastmodified:
    datatype: datetime
    nullable: True
  x:
    datatype: decimal
    nullable: True
  y:
    datatype: decimal
    nullable: True
  photo:
    datatype: text
    nullable: True
